myHotel/Controllers/BookingController.cs
using myHotel.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace myHotel.Controllers
{
    public class BookingController : Controller
    {
        private HotelContext _context;
        public BookingController()
        {
            _context = new HotelContext();
        }
        public ActionResult Index()
        {
            if (Session["UserName"] != null && Session["UserName"].ToString() == "Admin")
            {
                var buk = _context.bookings.ToList();
                return View(buk);
            }
            // int numVal = Int32.Parse("-105");
            if (Session["UserName"] != null)
            {
                var idd = Int32.Parse(Session["UserID"].ToString());

                var book = _context.bookings.Where(b => b.CustomerId == idd).ToList();
                return View(book);
                

            }
            return HttpNotFound();
        }

        public ActionResult New(int id)
        {
            Booking book = new Booking();
            TempData["rid"] = id;
            
            
            return View(book);
        }


       


        public ActionResult Save(Booking booking)
        {
            Console.WriteLine(booking.Id);
            if (!ModelState.IsValid)
            {
                Booking book = new Booking();
                return View("New", book);
            }
            else if (booking.Id == 0)
            {
                var room = _context.rooms.Single(r => r.Id == booking.RoomId);
                if (room.ToalAvailable < 1)
                {
                    return View("Index", "Room");
                }

                room.ToalAvailable--;
                booking.RoomNo = room.ToalAvailable + 100;
                    booking.BookingDate= DateTime.Today;
                _context.bookings.Add(booking);
            }
            else
            {
                

                var bookId = _context.bookings.Single(c => c.Id == booking.Id);
                bookId.CheckIn = booking.CheckIn;
                bookId.CheckOut = booking.CheckOut;
                bookId.CustomerId = booking.CustomerId;
                    bookId.RoomId = booking.RoomId;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            _context.SaveChanges();

            return RedirectToAction("Index", "Room");
        }

        public ActionResult Edit(int id)
        {

            var book = _context.bookings.SingleOrDefault(b => b.Id == id);
            TempData["rid"] = book.RoomId;

            if (book == null)

            {
                return HttpNotFound();
            }

            Booking books = new Booking();
            books = book;
            return View("New", books);
        }


        public ActionResult Delete(int id)
        {
            Booking booking = _context.bookings.Single(b => b.Id == id);
            var room = _context.rooms.Single(r => r.Id == booking.RoomId);
            var buk = _context.bookings.SingleOrDefault(b => b.Id == id);

            if (buk == null)

            {
                return HttpNotFound();
            }
            
            _context.bookings.Remove(buk);
            room.ToalAvailable++;
            _context.SaveChanges();

            var idd = Int32.Parse(Session["UserID"].ToString());

            var book = _context.bookings.Where(b => b.CustomerId == idd).ToList();

            return View("Index",book);

        }


        public ActionResult Search()
        {
            Booking book = new Booking();
            return View();
        }
        public ActionResult SearchResult(Booking booking)
        {
            var from = booking.CheckIn;
            var to = booking.CheckOut;

            Console.WriteLine(from);


            var obj = _context.bookings.Where(a => DbFunctions.TruncateTime(a.CheckIn) < DbFunctions.TruncateTime(booking.CheckIn) && DbFunctions.TruncateTime(a.CheckOut) > DbFunctions.TruncateTime(booking.CheckOut)).ToList();

            return View("Index",obj);
        }


        public ActionResult Today()
        {
            var today = DateTime.Now;
            var obj = _context.bookings.Where(a => DbFunctions.TruncateTime(a.BookingDate) == today.Date).ToList();
            return View("Index",obj);

        }
    }


}

myHotel/Controllers/CustomerController.cs
using myHotel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace HotmyHotelel.Controllers
{
    public class CustomerController : Controller
    {
        private HotelContext _context;
        public CustomerController()
        {
            _context = new HotelContext();
        }

        public ActionResult New()
        {
            Customer customer = new Customer();

            return View(customer);
        }

        public ActionResult Save(Customer cust)
        {
           
            if (!ModelState.IsValid)
            {
                Customer customer = new Customer();
                return View("New", customer);
            }
            if (cust.Id == 0)
            {
                _context.customers.Add(cust);
               

            }
           
            else
            {


                var customerId = _context.customers.Single(c => c.Id == cust.Id);
                customerId.Name = cust.Name;
                customerId.Mobile = cust.Mobile;
                customerId.Address = cust.Address;
                customerId.Adhar = cust.Adhar;
                customerId.Email = cust.Email;
                customerId.Password = cust.Password;
                TempData["rid"] = "profile Edited";
                _context.SaveChanges();


                return RedirectToAction("Edit");

            }
            TempData["rid"]="Form Submitted";
            _context.SaveChanges();
            

            return RedirectToAction("New");
        }

        public ActionResult Edit()
        {
            int id = Int32.Parse(Session["UserID"].ToString());
            

            var cust = _context.customers.SingleOrDefault(c => c.Id == id);
            if (cust == null)
            {
                return HttpNotFound();
            }
            Customer customerr = new Customer();
            customerr = cust;
            return View("New", customerr);
        }


        public JsonResult IsEmailAvailable(string Email)
        {
            if(Session["UserId"]!=null)
            {
                return Json(_context.customers.Any(c => c.Email == Email), JsonRequestBehavior.AllowGet);
            }


            return Json(!_context.customers.Any(c => c.Email == Email),JsonRequestBehavior.AllowGet);
        }


       
    }

}  



 

myHotel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>


@{ 
    var name="";
}
    @if (Session["UserName"] != null)
    {

        name = Session["UserName"].ToString();
    }




  
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hotel", "Index", "Home", new { area = "" }, new { @class = "navbar-brand"})
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                     
                      @if (name != "Admin")
                      {
                    <li>@Html.ActionLink("Check Room", "Index", "Room")</li>
                      }


                    @if (Session["UserName"] != null && name!="Admin")
                    {

                    <li>@Html.ActionLink("Profile", "Edit", "Customer")</li>
                    <li>@Html.ActionLink("View Bookings", "Index", "Booking")</li>
                    }
                </ul>
                
                    @if (name == "Admin")
                    { 
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Room", "Detaill", "Room")</li>
                    <li>@Html.ActionLink("Add Rooms", "New", "Room")</li>
                    <li>@Html.ActionLink("View Booking", "Index", "Booking")</li>

                </ul>
                }
                @if (Session["UserID"] == null)
                {

                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Register", "New", "Customer")</li>
                    <li>@Html.ActionLink("Log in", "Login", "Home")</li>
                </ul>
                }

                 @if (Session["UserName"] != null)
                 {
                       <ul class="nav navbar-nav navbar-right",color="white">
                         <li> <h4 style="color:gray"> Welcome @Session["UserName"].ToString() !!</h4></li>
                              
                              <li>@Html.ActionLink("Log Off", "LogOff", "Home")</li>
                        </ul>
                }
</div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>